### ISSUE TITLE
It looks like it doesn't work anymore

### ISSUE THREAD

**Issue by theRealSuperMario** [rockiger/recentpages#3]
I tried it with the current sim (0.73) and it would not work anymore

```python
ERROR: Could not load plugin recentpages
Traceback (most recent call last):
  File "/Users/sandrobraun/Programme_src/zim-desktop-wiki/zim/gui/preferencesdialog.py", line 362, in __init__
    klass = self.plugins.get_plugin_class(key)
  File "/Users/sandrobraun/Programme_src/zim-desktop-wiki/zim/plugins/__init__.py", line 420, in get_plugin_class
    mod = get_module(modname)
  File "/Users/sandrobraun/Programme_src/zim-desktop-wiki/zim/utils.py", line 35, in get_module
    mod = __import__(name)
  File "/Users/sandrobraun/.local/share/zim/plugins/recentpages.py", line 21, in <module>
    from zim.plugins import WindowExtension
ImportError: cannot import name 'WindowExtension' from 'zim.plugins' (/Users/sandrobraun/Programme_src/zim-desktop-wiki/zim/plugins/__init__.py)
```

I guess the aim API has changed.

Do you have any plans on adapting the code?

I also checked instant search - and it has adapted to the new api. So the changes might be minimal after all.

**Comment by rockiger** [comment]
Right now I don't have any plans to update the plugin.

I didn't use Zim for years. I switched to [https://fulcrum.wiki](https://fulcrum.wiki).

Having said that, I am happy to accept pull requests.
